server:
  port: ${PORT:8083}

spring:
  application:
    name: translation-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/translation-bot}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show.sql: true
    hibernate:
      ddl-auto: update


telegram:
  bot:
    token: ${BOT_TOKEN:7232909552:AAFJFWheZT3t0P7eE67CZuyrGdhJHEjCkFA}
    username: ${BOT_USERNAME:translationgroup_bot}
    username-admin: ${USERNAME_ADMIN:edzeeeee}
    bot-url: ${BOT_URL:https://t.me/translationgroup_bot}
    notification-chars: 100
  groups:
    starting-chars: ${STARTING_CHARS:10000}

crypto:
  pay:
    token: ${CRYPTO_TOKEN:24556:AAubQe1O5jSEyOlaNM4vI2Ljsf8M6yNBrb6}
    base-url: ${CRYPTO_PAY_URL:https://testnet-pay.crypt.bot/api}

yandex:
  translate:
    token: ${YANDEX_TRANSLATE_TOKEN:AQVNyPiEAuvo72PgR_vn3zNsZcPtNaAbgZd1-fLj}
    folder-id: ${FOLDER_ID:b1g918b29j7f1b60clmb}
    base-url: ${YANDEX_BASE_URL:https://translate.api.cloud.yandex.net/translate/v2}

proxyapi:
  openai:
    token: ${PROXYAPI_OPENAI_TOKEN:sk-sChXtxDe6d6sdMTOdq2GXcrxnJogiBz2}
    base_url: ${PROXYAPI_OPENAI_URL:https://api.proxyapi.ru/openai}
    model: ${OPENAI_MODEL:gpt-4o-mini}

google:
  translate:
    token: ${GOOGLE_TRANSLATE_TOKEN:AIzaSyCwoP7tTm7ygsQLN7JIAYQmgExNqs3ZMP4}